name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django pytest pytest-django pytest-mock pytest-asyncio celery redis black flake8 markdown-link-attr-modifier pydantic openai
        pip install -e .
    - name: Run lint
      run: |
        black --check .
        flake8 .
    - name: Run tests
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REDIS_URL: "redis://localhost:6379/0"
        DJANGO_SETTINGS_MODULE: "tests.test_settings"
        PYTHONPATH: "."
        CELERY_BROKER_URL: "redis://localhost:6379/0"
        CELERY_RESULT_BACKEND: "redis://localhost:6379/0"
        DJANGO_DB_NAME: ":memory:"
        DJANGO_DB_ENGINE: "django.db.backends.sqlite3"
      run: |
        python -m pytest tests/ -v --no-migrations --reuse-db
